use_frameworks!

platform :ios, '9.0'

target 'CNGradient_Example' do
  pod 'CNGradient', :path => '../'

  target 'CNGradient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
